defaults:
  - dataset: 2019/english
  - preprocessing: default
  - model: default

synthesis_list: zerospeech2020_datasets/2019/english/synthesis.json
in_dir: E:\datasets\zerospeech2020\2020\2019
out_dir: exp/zerospeech_vae/vc
checkpoint: exp/zerospeech_vae/model.pt